import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../models/api_error.dart';
import '../../models/order.dart';
import '../../state/auth_controller.dart';
import '../../state/ops_controller.dart';
import '../../theme/app_theme.dart';
import '../../utils/helpers.dart';
import '../../widgets/error_widget.dart';
import '../../widgets/loading_widget.dart';
import '../../widgets/period_toggle.dart';
import '../../widgets/stat_card.dart';

class EarningsScreen extends ConsumerStatefulWidget {
  const EarningsScreen({super.key});

  @override
  ConsumerState<EarningsScreen> createState() => _EarningsScreenState();
}

class _EarningsScreenState extends ConsumerState<EarningsScreen> {
  String _period = 'week';

  @override
  Widget build(BuildContext context) {
    final user = ref.watch(authControllerProvider).user;
    if (user?.isAgent != true) {
      return Scaffold(
        appBar: AppBar(title: const Text('Earnings')),
        body: const Center(
          child: Text('This page is for agents only.', style: TextStyle(color: AppColors.inkMuted)),
        ),
      );
    }

    final savings = ref.watch(costSavingsProvider(_period));
    final orders = ref.watch(earningsOrdersProvider(_period));
    final label = _period == 'month' ? 'This Month' : _period == 'all' ? 'All Time' : 'This Week';

    return Scaffold(
      appBar: AppBar(title: const Text('Earnings')),
      body: RefreshIndicator(
        color: AppColors.amber,
        onRefresh: () async {
          ref.invalidate(costSavingsProvider(_period));
          ref.invalidate(earningsOrdersProvider(_period));
        },
        child: ListView(
          padding: const EdgeInsets.fromLTRB(16, 8, 16, 32),
          children: [
            PeriodToggle(
              value: _period,
              options: const [('week', 'This Week'), ('month', 'This Month'), ('all', 'All Time')],
              onChanged: (v) => setState(() => _period = v),
            ),
            const SizedBox(height: 16),
            orders.when(
              loading: () => const LoadingWidget(label: 'Loading earnings'),
              error: (e, _) => AppErrorWidget(
                message: e is ApiError ? e.userMessage : 'Unable to load earnings.',
                onRetry: () => ref.invalidate(earningsOrdersProvider(_period)),
              ),
              data: (res) {
                final delivered = res.data.where((o) => o.status == 'delivered').toList();
                final total = delivered.fold<double>(0, (s, o) => s + o.paymentAmount);
                final avg = delivered.isEmpty ? 0.0 : total / delivered.length;
                return Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    SectionLabel('Delivery Earnings · $label'),
                    const Text(
                      'Sum of payment amount across delivered orders (simulated — no live payment gateway).',
                      style: TextStyle(color: AppColors.inkMuted, height: 1.35),
                    ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(child: StatCard(label: 'Total earned', value: formatInr2(total), emphasis: AppColors.go)),
                        const SizedBox(width: 8),
                        Expanded(child: StatCard(label: 'Delivered', value: '${delivered.length}', emphasis: AppColors.go)),
                      ],
                    ),
                    const SizedBox(height: 8),
                    StatCard(label: 'Avg per delivery', value: avg == 0 ? '—' : formatInr2(avg)),
                  ],
                );
              },
            ),
            const SizedBox(height: 20),
            savings.when(
              loading: () => const SizedBox.shrink(),
              error: (e, _) => Text(
                e is ApiError ? e.userMessage : 'Unable to load AI savings.',
                style: const TextStyle(color: AppColors.nogo),
              ),
              data: (s) {
                final m = s.metrics;
                return Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    SectionLabel('AI Cost Savings · $label · ${s.scope}'),
                    const Text(
                      'Savings generated by the GO/NO-GO system avoiding low-probability deliveries.',
                      style: TextStyle(color: AppColors.inkMuted, height: 1.35),
                    ),
                    const SizedBox(height: 12),
                    Row(
                      children: [
                        Expanded(child: StatCard(label: 'GO decisions', value: '${m.goCount}')),
                        const SizedBox(width: 8),
                        Expanded(child: StatCard(label: 'Trips avoided', value: '${m.deliveriesAvoided}', emphasis: AppColors.go)),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        Expanded(child: StatCard(label: 'Fuel saved', value: '${m.fuelSavedLitres} L', emphasis: AppColors.go)),
                        const SizedBox(width: 8),
                        Expanded(child: StatCard(label: 'Total savings', value: formatInr(m.totalSavingsInr), emphasis: AppColors.go)),
                      ],
                    ),
                    const SizedBox(height: 16),
                    SectionLabel('Performance · $label'),
                    Row(
                      children: [
                        Expanded(child: StatCard(label: 'Your success', value: percent1(m.successRateWithAi), emphasis: AppColors.go)),
                        const SizedBox(width: 8),
                        Expanded(child: StatCard(label: 'Area baseline', value: percent1(m.baselineSuccessRate))),
                      ],
                    ),
                    const SizedBox(height: 8),
                    StatCard(
                      label: 'vs Baseline',
                      value: '${m.improvementPct >= 0 ? '+' : ''}${m.improvementPct}%',
                      emphasis: m.improvementPct >= 0 ? AppColors.go : AppColors.nogo,
                    ),
                  ],
                );
              },
            ),
            const SizedBox(height: 20),
            orders.when(
              loading: () => const SizedBox.shrink(),
              error: (_, _) => const SizedBox.shrink(),
              data: (res) {
                final rows = [...res.data]..sort((a, b) {
                    if (a.status == 'delivered' && b.status != 'delivered') return -1;
                    if (b.status == 'delivered' && a.status != 'delivered') return 1;
                    return (b.createdAt ?? '').compareTo(a.createdAt ?? '');
                  });
                return Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    SectionLabel('Order & Decision History · $label'),
                    if (rows.isEmpty)
                      const Text('No orders in this period.', style: TextStyle(color: AppColors.inkMuted))
                    else
                      ...rows.take(40).map(_HistoryRow.new),
                  ],
                );
              },
            ),
          ],
        ),
      ),
    );
  }
}

class _HistoryRow extends StatelessWidget {
  const _HistoryRow(this.order);
  final Order order;

  @override
  Widget build(BuildContext context) {
    final decision = order.effectiveDecision;
    return Padding(
      padding: const EdgeInsets.only(bottom: 8),
      child: SurfaceCard(
        child: Row(
          children: [
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(order.orderNumber, style: const TextStyle(fontWeight: FontWeight.w700)),
                  Text(order.customerName, style: const TextStyle(color: AppColors.inkMuted, fontSize: 13)),
                ],
              ),
            ),
            Text(
              decision.isEmpty ? '—' : decision,
              style: TextStyle(
                color: decision == 'GO' ? AppColors.go : decision == 'NO-GO' ? AppColors.nogo : AppColors.inkDim,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(width: 10),
            Text(
              formatInr(order.paymentAmount),
              style: TextStyle(
                color: order.status == 'delivered' ? AppColors.go : AppColors.ink,
                fontWeight: FontWeight.w600,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
